### ISSUE TITLE
关于mask策略

### ISSUE THREAD

**Issue by INGg** [BINE022/EEGPT#1]
作者您好，对于您的工作我十分感兴趣，您的代码写的十分优美，有几个点想向您请教一下，恳请您能解答一下：

对于mae策略来说，按照我的理解，mask_x存储的是mask掉的下标，mask_y和mask_y_bx存储的是没有unmask的下标，那么110行对应概率大于0.2的那些下标来说，它既不在mask_x中，也不在mask_y_bx和mask_y中，这里为什么要这么做呢？在论文中4式和7式中的“存在”符号是否代表这个意思。
<img width="873" alt="image" src="https://github.com/user-attachments/assets/2718c295-fc68-460e-a1cc-9efdca8fb19a">

**Comment by whiteram** [comment]
非常感谢您对我的工作表示出的兴趣和赞赏，我很高兴您对我的代码给予如此高的评价。我非常乐意回答您关于MAE策略的问题。

您对`mask_x`、`mask_y`和`mask_y_bx`的理解是正确的。`mask_x`存储的是被mask掉的下标，而`mask_y`和`mask_y_bx`存储的是没有被unmask的下标，即作为模型预测目标的patch的下标。关于您提到的第110行代码，您注意到了一个重要的细节。这里的做法是为了节省预训练阶段GPU显存占用的同时，保持预训练任务的难度。

具体来说，`mask_y`和`mask_y_bx`的区别在于，对于每个时间步i，有50%的概率，该时间步对应的所有patch下标会被存储到`mask_y`中（如代码第106行所示）。而对于没有被存储到`mask_y`的时间步i，我们会随机选择12个通道的patch下标存储到`mask_x`中（代码第103行），其余46个通道的patch下标则存储到`mask_y_bx`中（代码第104行）。为了在节省预训练阶段GPU显存占用，我们考虑减少作为预测目标的patch的数量。

考虑到模型需要根据`mask_x`中对应下标的patch来预测`mask_y_bx`中对应下标的patch，这可能比直接预测`mask_y`中对应下标的patch要容易一些，因为`mask_x`中包含了`mask_y_bx`中相同时间步下的12个通道的patch。因此，我们优先随机去掉`mask_y_bx`中的下标，以保持预训练任务的难度。

在论文中4式和7式中的“存在”符号不代表这个意思。

**Comment by INGg** [comment]
> 非常感谢您对我的工作表示出的兴趣和赞赏，我很高兴您对我的代码给予如此高的评价。我非常乐意回答您关于MAE策略的问题。
> 
> 您对`mask_x`、`mask_y`和`mask_y_bx`的理解是正确的。`mask_x`存储的是被mask掉的下标，而`mask_y`和`mask_y_bx`存储的是没有被unmask的下标，即作为模型预测目标的patch的下标。关于您提到的第110行代码，您注意到了一个重要的细节。这里的做法是为了节省预训练阶段GPU显存占用的同时，保持预训练任务的难度。
> 
> 具体来说，`mask_y`和`mask_y_bx`的区别在于，对于每个时间步i，有50%的概率，该时间步对应的所有patch下标会被存储到`mask_y`中（如代码第106行所示）。而对于没有被存储到`mask_y`的时间步i，我们会随机选择12个通道的patch下标存储到`mask_x`中（代码第103行），其余46个通道的patch下标则存储到`mask_y_bx`中（代码第104行）。为了在节省预训练阶段GPU显存占用，我们考虑减少作为预测目标的patch的数量。
> 
> 考虑到模型需要根据`mask_x`中对应下标的patch来预测`mask_y_bx`中对应下标的patch，这可能比直接预测`mask_y`中对应下标的patch要容易一些，因为`mask_x`中包含了`mask_y_bx`中相同时间步下的12个通道的patch。因此，我们优先随机去掉`mask_y_bx`中的下标，以保持预训练任务的难度。
> 
> 在论文中4式和7式中的“存在”符号不代表这个意思。

感谢您的回答，我已经明白了，但我认为您想说的应该是“`mask_x`中包含了`mask_y_bx`中相同时间步下的`后58-12个通道的patch`”
