### ISSUE TITLE
python version!

### ISSUE THREAD

**Issue by HaneenSu** [BINE022/EEGPT#2]
Hi,

I am wondering about the python version is used to create the venv?
When I do pip install -r requirements.txt, installation stops at torch-lfilter:

```
Running setup.py install for torch_lfilter ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for torch_lfilter did not run successfully.
```

**Comment by INGg** [comment]
you can first install torch==2.0.0, and then use `pip install torch_lfilter==0.0.3 -i https://pypi.org/simple`. after that you can use `pip install -r requirements.txt` successfully

**Comment by HaneenSu** [comment]
Thank you this worked! I also had gcc missing, and adding it resolved the issue.
